"""update website

Revision ID: aa78997d7252
Revises: 7654d50ec91a
Create Date: 2025-10-29 16:48:22.488356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa78997d7252'
down_revision: Union[str, None] = '7654d50ec91a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websites', sa.Column('widget_color', sa.String(length=7), nullable=True))
    op.add_column('websites', sa.Column('widget_size', sa.String(length=20), nullable=True))
    op.add_column('websites', sa.Column('widget_position', sa.String(length=20), nullable=True))
    op.add_column('websites', sa.Column('widget_icon', sa.String(length=255), nullable=True))
    op.add_column('websites', sa.Column('placeholder_text', sa.String(length=200), nullable=True))
    op.add_column('websites', sa.Column('show_powered_by', sa.Boolean(), nullable=True))
    op.add_column('websites', sa.Column('custom_css', sa.Text(), nullable=True))
    op.add_column('websites', sa.Column('auto_open_delay', sa.Integer(), nullable=True))
    op.add_column('websites', sa.Column('enable_sound', sa.Boolean(), nullable=True))
    op.add_column('websites', sa.Column('enable_file_upload', sa.Boolean(), nullable=True))
    op.add_column('websites', sa.Column('allowed_file_types', sa.JSON(), nullable=True))
    op.add_column('websites', sa.Column('widget_status', sa.String(length=20), nullable=True))
    op.add_column('websites', sa.Column('business_hours_enabled', sa.Boolean(), nullable=True))
    op.add_column('websites', sa.Column('domain_verified', sa.Boolean(), nullable=True))
    op.add_column('websites', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.add_column('websites', sa.Column('allowed_domains', sa.JSON(), nullable=True))
    op.add_column('websites', sa.Column('widget_api_key', sa.String(length=100), nullable=True))
    op.add_column('websites', sa.Column('total_visitors', sa.Integer(), nullable=True))
    op.add_column('websites', sa.Column('total_conversations', sa.Integer(), nullable=True))
    op.add_column('websites', sa.Column('conversion_rate', sa.Integer(), nullable=True))
    op.alter_column('websites', 'embed_code',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('websites', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('websites', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_websites_widget_api_key'), 'websites', ['widget_api_key'], unique=True)
    op.drop_column('websites', 'widget_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websites', sa.Column('widget_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_websites_widget_api_key'), table_name='websites')
    op.alter_column('websites', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('websites', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('websites', 'embed_code',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.drop_column('websites', 'conversion_rate')
    op.drop_column('websites', 'total_conversations')
    op.drop_column('websites', 'total_visitors')
    op.drop_column('websites', 'widget_api_key')
    op.drop_column('websites', 'allowed_domains')
    op.drop_column('websites', 'verified_at')
    op.drop_column('websites', 'domain_verified')
    op.drop_column('websites', 'business_hours_enabled')
    op.drop_column('websites', 'widget_status')
    op.drop_column('websites', 'allowed_file_types')
    op.drop_column('websites', 'enable_file_upload')
    op.drop_column('websites', 'enable_sound')
    op.drop_column('websites', 'auto_open_delay')
    op.drop_column('websites', 'custom_css')
    op.drop_column('websites', 'show_powered_by')
    op.drop_column('websites', 'placeholder_text')
    op.drop_column('websites', 'widget_icon')
    op.drop_column('websites', 'widget_position')
    op.drop_column('websites', 'widget_size')
    op.drop_column('websites', 'widget_color')
    # ### end Alembic commands ###
