"""remove auditlog relationship

Revision ID: be1f92676f2e
Revises: REPLACE_WITH_YOUR_REVISION_ID
Create Date: 2025-10-25 18:54:37.529096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be1f92676f2e'
down_revision: Union[str, None] = 'REPLACE_WITH_YOUR_REVISION_ID'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_api_keys_key_id'), 'api_keys', ['key_id'], unique=False)
    op.create_index(op.f('ix_billing_records_billing_id'), 'billing_records', ['billing_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_message_id'), 'chat_messages', ['message_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_session_id'), 'chat_sessions', ['session_id'], unique=False)
    op.create_unique_constraint(None, 'resource_allocations', ['company_id'])
    op.create_index(op.f('ix_usage_analytics_analytics_id'), 'usage_analytics', ['analytics_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_analytics_analytics_id'), table_name='usage_analytics')
    op.drop_constraint(None, 'resource_allocations', type_='unique')
    op.drop_index(op.f('ix_chat_sessions_session_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_messages_message_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_billing_records_billing_id'), table_name='billing_records')
    op.drop_index(op.f('ix_api_keys_key_id'), table_name='api_keys')
    # ### end Alembic commands ###
